# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/worbb/Desktop/IMA/FPGA/SW_Sensor/SW_Sensor.srcs/sources_1/ip/RS232_fifo/RS232_fifo.xci
# IP: The module: 'RS232_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/worbb/Desktop/IMA/FPGA/SW_Sensor/SW_Sensor.gen/sources_1/ip/RS232_fifo/RS232_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'RS232_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/worbb/Desktop/IMA/FPGA/SW_Sensor/SW_Sensor.gen/sources_1/ip/RS232_fifo/RS232_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RS232_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/worbb/Desktop/IMA/FPGA/SW_Sensor/SW_Sensor.srcs/sources_1/ip/RS232_fifo/RS232_fifo.xci
# IP: The module: 'RS232_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/worbb/Desktop/IMA/FPGA/SW_Sensor/SW_Sensor.gen/sources_1/ip/RS232_fifo/RS232_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'RS232_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/worbb/Desktop/IMA/FPGA/SW_Sensor/SW_Sensor.gen/sources_1/ip/RS232_fifo/RS232_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RS232_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
