# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/worbb/Desktop/IMA/Sensor-ondas-espin/2025-Heterodyne-Spartan7/SW_Sensor/SW_Sensor.srcs/sources_1/ip/I2C_fifo/I2C_fifo.xci
# IP: The module: 'I2C_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/worbb/Desktop/IMA/Sensor-ondas-espin/2025-Heterodyne-Spartan7/SW_Sensor/SW_Sensor.gen/sources_1/ip/I2C_fifo/I2C_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2C_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/worbb/Desktop/IMA/Sensor-ondas-espin/2025-Heterodyne-Spartan7/SW_Sensor/SW_Sensor.gen/sources_1/ip/I2C_fifo/I2C_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2C_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/worbb/Desktop/IMA/Sensor-ondas-espin/2025-Heterodyne-Spartan7/SW_Sensor/SW_Sensor.srcs/sources_1/ip/I2C_fifo/I2C_fifo.xci
# IP: The module: 'I2C_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/worbb/Desktop/IMA/Sensor-ondas-espin/2025-Heterodyne-Spartan7/SW_Sensor/SW_Sensor.gen/sources_1/ip/I2C_fifo/I2C_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2C_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/worbb/Desktop/IMA/Sensor-ondas-espin/2025-Heterodyne-Spartan7/SW_Sensor/SW_Sensor.gen/sources_1/ip/I2C_fifo/I2C_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'I2C_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
